# Generated by Django 3.1.5 on 2021-01-21 13:23

from django.db import migrations
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
    ]
