# Generated by Django 3.1.5 on 2021-01-25 05:09

from django.db import migrations
import django.utils.timezone
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210122_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='text_rendered',
            field=markdownfield.models.RenderedMarkdownField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=markdownfield.models.MarkdownField(rendered_field='text_rendered'),
        ),
    ]
