# Generated by Django 3.1.5 on 2021-01-25 13:23

from django.db import migrations
import django.utils.timezone
import markdownfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210125_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='blurb',
            field=markdownfield.models.MarkdownField(default=django.utils.timezone.now, rendered_field='blurb_rendered'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='blurb_rendered',
            field=markdownfield.models.RenderedMarkdownField(default='', max_length=250),
        ),
    ]
